version: '3.2'
services:
  zero:
    image: 'dgraph/dgraph:latest'
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - '5080:5080'
      - '6080:6080'
    restart: on-failure
    command: 'dgraph zero --bindall=true --my=zero:5080'
  alpha:
    image: 'dgraph/dgraph:latest'
    depends_on:
      - zero
    volumes:
      - './${pwd}/service:/dgraph/service'
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8080:8080
      - 7080:7080
      - 9080:9080
    tty: true
    restart: on-failure
    command: 'bash ./service/bulk-it-or-not-bulk-it.sh'
  ratel:
    image: 'dgraph/dgraph:latest'
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8000:8000
    command: dgraph-ratel
volumes:
  dgraph:
    driver: local
